### ISSUE TITLE
Version docker images

### ISSUE THREAD

**Issue by onedr0p** [raetha/wyzesense2mqtt#24]
Hi! Thanks so much for creating this image, I was all set to create my own from the upstream project before I found this.

I am curious if you plan to support version tags on the docker images? This would be great incase we need to rollback to a previous version.

For example:

current version would be the same image with different tags:
```
raetha/wyzesense2mqtt:v1.1.0
raetha/wyzesense2mqtt:latest
```

previous versions:
```
raetha/wyzesense2mqtt:v1.0.9
raetha/wyzesense2mqtt:v1.0.8
...
```

**Comment by raetha** [comment]
Hi Devin (@onedr0p), I'd actually originally set things up with releases when I was first figuring out Docker Hub, but removed it for some reason. I honestly can't remember my logic, and yours makes a ton of sense, so I'll get them back in place. I'll update here once that is complete.

**Comment by raetha** [comment]
Ok, I believe I've added the required configuration in Docker, unfortunately it looks like it may not start generating them until the next release, so hopefully I'll know as soon as I can polish 1.1 and get that pushed. I'm hoping by this weekend. I'll leave this open until I confirm that they are generating going forward.

**Comment by onedr0p** [comment]
Thanks @raetha !
