### ISSUE TITLE
Detect sensors already paired by HACS Wyzesense integration

### ISSUE THREAD

**Issue by SamuelCarson** [raetha/wyzesense2mqtt#37]
Will this component detect sensors already paired by the Wyzesense integration or will they need to be unpaired and re-paired when switching from the HACS integration to wysesense2MQTT

**Comment by SamuelCarson** [comment]
Will this component detect sensors already paired by the Wyzesense integration or will they need to be unpaired and re-paired

**Comment by raetha** [comment]
Hi @SamuelCarson, it should detect all sensors paired with the bridge, and automatically add them to the sensors.yaml file when it runs. They won't have intuitive names at that point, but you can then rename them in the config file or directly in Home Assistant after they are discovered.

**Comment by SamuelCarson** [comment]
Bridge tool shows:
15 sensors paired:
	Sensor: 779C04F4
	Sensor: 779C04C9
	Sensor: 779D582D
	Sensor: 7788277B
	Sensor: 7786E6CD
	Sensor: 77881982
	Sensor: 77882771
	Sensor: 77882895
	Sensor: 77882CDF
	Sensor: 77882C6B
	Sensor: 778828A0
	Sensor: 77869E12
	Sensor: 77882724
	Sensor: 77882C9A
	Sensor: 7786E6B8
Home Assistant shows these as Unavailable and wyzesense2mqtt has NOT updated the sensors.yaml file. I  am completely stumped

**Comment by SamuelCarson** [comment]
Figured it out. There was no /wyzesense2mqtt/logs directory.
Several changes to linux install are necessary, especially if running on a raspberry pi. Complete updated instructions are in the following file
[Install wyzesense2mqtt.txt](https://github.com/raetha/wyzesense2mqtt/files/5184938/Install.wyzesense2mqtt.txt)

**Comment by raetha** [comment]
@SamuelCarson really appreciate the updated docs. I've incorporated those changes into the devel instructions, and they will update fully on the 1.2 release.
