### ISSUE TITLE
Sensors.yaml file not optional

### ISSUE THREAD

**Issue by AK5nowman** [raetha/wyzesense2mqtt#44]
## Describe the Bug

the Sensors.yaml file has to be defined and it has to had at least a single entry, contrary to what the instructions set says. There are no checks to see if the SENSORS global variable is set throughout the code and will fail silently in multiple locations. 

### Steps To Reproduce

1. Remove sensors.yaml file and start up

### Expected Behavior

I expect the app to create and write the sensor data to the sensor.yaml file

**Comment by tehstevo** [comment]
Had the same experience in my install tonight.  Putting a bogus entry into the sensors.yaml file resolved it.

**Comment by raetha** [comment]
This is now fixed in the devel branch. Thanks @AK5nowman for the PR that gave an easy way to handle this.

Will go to master branch with 1.2, hopefully this weekend.
