### ISSUE TITLE
Devel branch - service won't start without permission tweeks

### ISSUE THREAD

**Issue by dennyfmn** [raetha/wyzesense2mqtt#48]
I just did a fresh install of the devel branch and had to do a few things before the service would start.

I am running the systemd version of the installation.

For several months, I have been running rev 1.0 that I had patched to publish the sensor_name in the MQTT output. I decided to update to the latest devel branch to start using the newest code that supports the sensor_name in MQTT natively.

For a fresh install of devel branch:
cd /tmp
git clone -b devel https://github.com/raetha/wyzesense2mqtt.git

I moved my old version off to the side and set up the new one.
After copying the tree to /wyzesense2mqtt I found that the config and logs directories did not exist
mkdir config
mkdir logs

After setting up all the yaml files, I found that the service would not start. The issue was that the python and shell scripts were not executable.

chmod +x *.py
chmod +x *.sh

Fixed the problem.

**Comment by raetha** [comment]
@dennyfmn, thanks so much for passing this along. I've updated the readme to include instructions to create config and logs folders, and also changed the default permissions for the Python and shell scripts to include the executable bit. These are in devel now, so if you update, hopefully you'll see the right permissions now.
