### ISSUE TITLE
More friendly entity IDs in Home Assistant

### ISSUE THREAD

**Issue by drinfernoo** [raetha/wyzesense2mqtt#56]
**Is your feature request related to a problem? Please describe.**
When a sensor is paired to the bridge, the entities that get published for discovery are added to HA with an entity ID, something like `binary_sensor.wyzesense_abcdefgh`. It would be nice if they could be added to match the name of the sensor as defined in `sensors.yaml`.

**Comment by AK5nowman** [comment]
@drinfernoo Hey I think this was kind of talked about [here](https://github.com/raetha/wyzesense2mqtt/pull/45#issuecomment-735037133). I think he preferred to keep the sensors physical naming for the topic as opposed to the semantic naming. His reasoning if in that post I linked. I don't use HASS so it might make more sense for you.
